#!/bin/sh
# Refresh the crawler/social-bot User-Agent map that routes bot traffic to the
# server-rendered SEO pages. Pulls the maintained token list from ai.robots.txt
# and merges it with a static baseline. Non-fatal: keeps the existing map on any
# failure, so a bad network or upstream change can never take the site down.
#
# Runs inside the nginx container (only place with nginx + egress), invoked at
# boot by docker-entrypoint.sh and daily via /etc/periodic/daily.
set -u

SRC="https://raw.githubusercontent.com/ai-robots-txt/ai.robots.txt/main/robots.txt"
CONF="/etc/nginx/conf.d/00-render-seo-map.conf"

# Tokens always matched: social/embed scrapers the ai.robots.txt list omits,
# plus current AI crawlers and search engines.
BASELINE='googlebot|bingbot|yandexbot|duckduckbot|baiduspider|applebot|petalbot|seznambot|bytespider|sogou|exabot|ia_archiver|semrushbot|ahrefsbot|mj12bot|dotbot|rogerbot|screaming frog|gptbot|oai-searchbot|oai-adsbot|chatgpt-user|claudebot|claude-web|claude-user|claude-searchbot|anthropic-ai|perplexitybot|perplexity-user|ccbot|google-extended|googleother|google-inspectiontool|amazonbot|meta-externalagent|facebookexternalhit|twitterbot|discordbot|linkedinbot|slackbot|telegrambot|whatsapp|pinterestbot|redditbot|embedly|quora link preview|skypeuripreview|vkshare|w3c_validator|bitlybot|tumblr|iframely|mistralai-user|duckassistbot|google-cloudvertexbot'

# Upstream tokens too short/generic to substring-match safely, or robots.txt
# control tokens that are not real User-Agents.
DENY='^(code|devin|cursor|spider|scrapy|operator|trae|lcc|yak|applebot-extended)$'

# Whitelist the character set so a malicious/compromised upstream cannot inject
# quotes, semicolons, newlines or nginx directives into the generated config.
TOKEN_RE='^[a-z0-9._/ -]+$'

log() { echo "update-render-seo-map: $*" >&2; }

fetch() {
    if command -v curl >/dev/null 2>&1; then
        curl -fsSL --max-time 20 "$SRC"
    else
        wget -q -T 20 -O - "$SRC"
    fi
}

upstream=$(fetch 2>/dev/null \
    | awk 'tolower($1)=="user-agent:" { gsub(/\r/,"",$2); if ($2!="") print tolower($2) }' \
    | sort -u \
    | grep -vxE "$DENY" \
    | grep -E "$TOKEN_RE" \
    | awk 'length>=5')

if [ -z "$upstream" ]; then
    log "no upstream tokens fetched; keeping existing map"
    exit 0
fi

all=$( { printf '%s\n' "$BASELINE"; printf '%s\n' "$upstream"; } \
    | tr '|' '\n' | awk 'NF' | sort -u \
    | sed -e 's/[][\\.^$|?*+(){}]/\\&/g' \
    | paste -s -d '|')

tmp="$CONF.tmp"
{
    echo '# Generated by update-render-seo-map.sh; do not edit by hand.'
    echo '# Crawlers/social scrapers get the server-rendered SEO pages; browsers get the SPA.'
    echo 'map $http_user_agent $render_seo {'
    echo '    default "";'
    printf '    "~*(%s)" "1";\n' "$all"
    echo '}'
} > "$tmp"

cp -f "$CONF" "$CONF.bak" 2>/dev/null || { log "cannot back up existing map"; rm -f "$tmp"; exit 1; }
mv -f "$tmp" "$CONF"

if nginx -t >/dev/null 2>&1; then
    rm -f "$CONF.bak"
    # -s (non-empty): the base image ships an empty /run/nginx.pid, so only
    # reload when nginx is actually running (after boot, or via the daily cron).
    if [ -s /run/nginx.pid ]; then
        if nginx -s reload; then
            log "map refreshed and nginx reloaded"
        else
            log "map refreshed but nginx reload failed"
        fi
    else
        log "map refreshed"
    fi
else
    log "generated map failed nginx -t; rolling back"
    [ -f "$CONF.bak" ] && mv -f "$CONF.bak" "$CONF"
    exit 1
fi
