services:
  db:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./lncrawler-api
    restart: unless-stopped
    volumes: &api-volumes
      - ./lncrawler-api:/app/lncrawler-api
      - ./Lightnovels:/app/Lightnovels
      - ./imports:/app/imports
      - ./lncrawler-api/logs:/app/lncrawler-api/logs
      - ./lncrawler-crawler:/app/lncrawler-crawler
    environment: &api-env
      - SITE_URL=${SITE_URL}
      - SITE_API_URL=${SITE_API_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - CORS_ALLOW_ALL_ORIGINS=${CORS_ALLOW_ALL_ORIGINS}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - EMAIL_SENDER_NAME=${EMAIL_SENDER_NAME}
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "/app/lncrawler-api/start.sh"]

  crawler:
    build: ./lncrawler-api
    restart: unless-stopped
    volumes: *api-volumes
    environment: *api-env
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started
    command: ["sh", "/app/lncrawler-api/start_crawler.sh"]

  scheduler:
    build: ./lncrawler-api
    restart: unless-stopped
    volumes: *api-volumes
    environment: *api-env
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started
    command: ["sh", "/app/lncrawler-api/start_scheduler.sh"]

  frontend:
    build:
      context: ./lncrawler-frontend
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    restart: unless-stopped
    depends_on:
      - api

  nginx-proxy:
    build: ./nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"  # The main entry point
    volumes:
      - ./lncrawler-api/static:/static
      - ./lncrawler-api/media:/media
      - ./Lightnovels:/lightnovels
    environment:
      - API_HOST=${API_HOST}
      - FRONTEND_HOST=${FRONTEND_HOST}
    depends_on:
      - api
      - frontend

volumes:
  postgres_data:
