services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      # Database credentials
      # Replace with your own values
      - POSTGRES_DB=lncrawler
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=biyoo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./lncrawler-api
    volumes:
      - ./lncrawler-api:/app/lncrawler-api
      - ./Lightnovels:/app/Lightnovels
      - ./imports:/app/imports
      - ./lncrawler-api/logs:/app/lncrawler-api/logs
      - ./dipudb-lncrawler-jere344-patches:/app/dipudb-lncrawler-jere344-patches
    environment:
      - SITE_URL=http://localhost # Your website frontend URL
      - SITE_API_URL=http://api.localhost # Your website API URL
      - SECRET_KEY=django-insecure-h=mhg#$sm-l4o240a+m#f=98$)+m0_3p0*%v%_*w)bi(d3f1u_ # Your Django secret key. You can generate one using `django-admin startproject --generate-secret-key`
      - DEBUG=False # Set to False in production
      - CORS_ALLOW_ALL_ORIGINS=False # Set to False in production

      # Django Admin credentials. Can be changed at runtime from the admin panel
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=jeremy.guerin34@yahoo.com
      - DJANGO_SUPERUSER_PASSWORD=admin

      # Database credentials. Replace with the values used above for the db service
      - POSTGRES_DB=lncrawler
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=biyoo

      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

      # Brevo email service credentials (for password reset emails)
      - BREVO_API_KEY= # Your Brevo API key
      - DEFAULT_FROM_EMAIL=no-reply@lncrawler.monster # Your Brevo sender email
      - EMAIL_SENDER_NAME=LNCrawler # Your Brevo sender name
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "/app/lncrawler-api/start.sh"]
  
  frontend:
    build:
      context: ./lncrawler-frontend
      args:
        - VITE_API_BASE_URL=http://api.localhost # Your website API URL
    depends_on:
      - api
    
  nginx-proxy:
    build: ./nginx-proxy
    ports:
      - "80:80"  # The main entry point
    volumes:
      - ./lncrawler-api/static:/static
      - ./lncrawler-api/media:/media
      - ./Lightnovels:/lightnovels
    environment:
      - API_HOST=api.localhost # Your API host
      - FRONTEND_HOST=localhost # Your frontend host
    depends_on:
      - api
      - frontend

volumes:
  postgres_data:
