services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      # Database credentials
      # Replace with your own values
      - POSTGRES_DB=lncrawler
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=biyoo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./lncrawler-api
    volumes:
      - ./lncrawler-api:/app/lncrawler-api
      - ./Lightnovels:/app/Lightnovels
      - ./imports:/app/imports
      - ./lncrawler-api/logs:/app/lncrawler-api/logs
      - ./dipudb-lncrawler-jere344-patches:/app/dipudb-lncrawler-jere344-patches
    ports:
      - "8186:8000"
    environment:
      - SITE_URL=http://localhost:8185 # Your website frontend URL
      - SITE_API_URL=http://localhost:8186 # Your website API URL
      - CORS_ORIGIN_WHITELIST=http://localhost:8185,http://127.0.0.1:8185,http://frontend # Your website frontend URL. You may want the http and https versions
      - ALLOWED_HOSTS=localhost,127.0.0.1,api # Your website API domains
      - SECRET_KEY=django-insecure-h=mhg#$sm-l4o240a+m#f=98$)+m0_3p0*%v%_*w)bi(d3f1u_ # Your Django secret key. You can generate one using `django-admin startproject --generate-secret-key`
      - DEBUG=True # Set to False in production
      - CORS_ALLOW_ALL_ORIGINS=True # Set to False in production

      # Django Admin credentials. Can be changed at runtime from the admin panel
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=jeremy.guerin34@yahoo.com
      - DJANGO_SUPERUSER_PASSWORD=admin

      # Database credentials. Replace with the values used above for the db service
      - POSTGRES_DB=lncrawler
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=biyoo

      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "/app/lncrawler-api/start.sh"]

  frontend:
    build:
      context: ./lncrawler-frontend
      args:
        - VITE_API_BASE_URL=http://localhost:8186 # Your website API URL
    ports:
      - "8185:80"
    depends_on:
      - api

volumes:
  postgres_data:
