# Generated by Django 5.2.1 on 2025-05-10 00:03

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("searching", "Searching"),
                            ("search_completed", "Search Completed"),
                            ("downloading", "Downloading"),
                            ("download_completed", "Download Completed"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("query", models.CharField(blank=True, max_length=255, null=True)),
                ("job_pid", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("progress", models.IntegerField(default=0)),
                ("total_items", models.IntegerField(default=0)),
                (
                    "search_results",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "selected_novel",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "output_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("output_files", models.JSONField(blank=True, default=list, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
