# Generated by Django 5.2.1 on 2025-05-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lncrawler_api", "0002_author_editor_genre_novel_tag_translator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="import_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
