# Generated by Django 5.2.1 on 2025-05-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lncrawler_api", "0003_job_import_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="novelfromsource",
            name="source_slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
