# Generated by Django 5.2.1 on 2025-05-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lncrawler_api", "0004_novelfromsource_source_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chapter",
            old_name="file_path",
            new_name="chapter_path",
        ),
        migrations.AddField(
            model_name="novel",
            name="novel_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="novelfromsource",
            name="cover_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="novelfromsource",
            name="source_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
