# Generated by Django 5.2.1 on 2025-05-11 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lncrawler_api", "0005_rename_file_path_chapter_chapter_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="novelfromsource",
            name="downvotes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="novelfromsource",
            name="upvotes",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="SourceVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "vote_type",
                    models.CharField(
                        choices=[("up", "Upvote"), ("down", "Downvote")], max_length=4
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="lncrawler_api.novelfromsource",
                    ),
                ),
            ],
            options={
                "unique_together": {("source", "ip_address")},
            },
        ),
    ]
