# Generated by Django 5.2.1 on 2025-05-12 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lncrawler_api", "0010_comment_downvotes_comment_upvotes_commentvote"),
    ]

    operations = [
        migrations.CreateModel(
            name="NovelViewCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("views", models.BigIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "novel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_count",
                        to="lncrawler_api.novel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyNovelView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_week", models.CharField(max_length=6)),
                ("views", models.PositiveIntegerField(default=0)),
                (
                    "novel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_views",
                        to="lncrawler_api.novel",
                    ),
                ),
            ],
            options={
                "unique_together": {("novel", "year_week")},
            },
        ),
    ]
