# Generated by Django 5.2.1 on 2025-05-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lncrawler_api", "0011_novelviewcount_weeklynovelview"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="output_novel_url",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
