# Generated by Django 5.2.1 on 2025-05-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lncrawler_api", "0012_job_output_novel_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="output_novel_url",
            new_name="output_source_path",
        ),
    ]
