# Generated by Django 5.2.1 on 2025-05-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lncrawler_api", "0014_rename_output_source_path_job_output_source_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="output_source_slug",
            new_name="output_slug",
        ),
    ]
