# Generated by Django 5.2.1 on 2025-05-16 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lncrawler_api", "0015_rename_output_source_slug_job_output_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedNovel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Reason why this novel is featured"
                    ),
                ),
                (
                    "novel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured",
                        to="lncrawler_api.novel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Featured Novel",
                "verbose_name_plural": "Featured Novels",
            },
        ),
    ]
