# Generated by Django 5.2.1 on 2025-05-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lncrawler_api", "0017_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="has_content",
            field=models.BooleanField(default=False),
        ),
    ]
