# Generated by Django 5.2.1 on 2025-05-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lncrawler_api", "0019_novelbookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="novel",
            name="comment_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
