# Generated by Django 5.2.1 on 2025-05-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lncrawler_api", "0022_comment_edited"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="novelfromsource",
            name="genres",
        ),
        migrations.RemoveField(
            model_name="chapter",
            name="success",
        ),
        migrations.RemoveField(
            model_name="novelfromsource",
            name="description",
        ),
        migrations.RemoveField(
            model_name="novelfromsource",
            name="source",
        ),
        migrations.AlterField(
            model_name="chapter",
            name="images",
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
    ]
