# Generated by Django 5.2.1 on 2025-05-25 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "lncrawler_api",
            "0023_remove_novelfromsource_genres_remove_chapter_success_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="NovelSimilarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "similarity",
                    models.FloatField(
                        default=0.0, help_text="Similarity score between 0 and 1"
                    ),
                ),
                (
                    "from_novel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similar_to",
                        to="lncrawler_api.novel",
                    ),
                ),
                (
                    "to_novel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="similar_from",
                        to="lncrawler_api.novel",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Novel Similarities",
                "unique_together": {("from_novel", "to_novel")},
            },
        ),
    ]
