# Generated by Django 5.2.1 on 2025-05-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lncrawler_api", "0024_novelsimilarity"),
    ]

    operations = [
        migrations.AddField(
            model_name="novelfromsource",
            name="overview_picture_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
