# Generated by Django 5.2.1 on 2025-05-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lncrawler_api", "0026_migrate_novel_tags_to_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="novelfromsource",
            name="novel_tags",
        ),
    ]
