# Generated by Django 5.2.1 on 2025-05-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lncrawler_api", "0029_review_reviewreaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="reaction_count",
        ),
    ]
