# Generated by Django 5.2.1 on 2025-05-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lncrawler_api", "0030_remove_review_reaction_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="novelfromsource",
            name="cover_min_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
