# Generated by Django 5.2.1 on 2025-05-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lncrawler_api", "0031_novelfromsource_cover_min_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="novelfromsource",
            name="cover_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="novelfromsource",
            name="novelupdates_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="novelfromsource",
            name="source_url",
            field=models.CharField(max_length=500),
        ),
    ]
