# Generated by Django 5.2.1 on 2025-05-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lncrawler_api", "0032_alter_novelfromsource_cover_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="novelfromsource",
            name="novelupdates_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
