# Generated by Django 5.2.1 on 2025-06-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lncrawler_api", "0034_auto_20250601_1205"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="chapter_path",
        ),
        migrations.RemoveField(
            model_name="job",
            name="job_pid",
        ),
        migrations.AlterField(
            model_name="chapter",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="volume_title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="novelfromsource",
            name="english_publisher",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="novelfromsource",
            name="original_publisher",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="novelfromsource",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="volume",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
