# Generated by Django 5.2.1 on 2025-06-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lncrawler_api', '0036_readinglist_readinglistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
