# Generated by Django 5.2.1 on 2025-08-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lncrawler_api", "0037_chapter_word_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for the task",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "interval_seconds",
                    models.PositiveIntegerField(help_text="Task interval in seconds"),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful execution time",
                        null=True,
                    ),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(help_text="Next scheduled execution time"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "locked_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Lock expiration time to prevent zombie locks",
                        null=True,
                    ),
                ),
                (
                    "worker_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of worker that locked this task",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if task failed"
                    ),
                ),
            ],
            options={
                "db_table": "scheduler_scheduled_task",
                "ordering": ["next_run_at"],
            },
        ),
    ]
