# Generated by Django 5.2.1 on 2026-10-02 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lncrawler_api', '0040_job_progress_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='lncrawler_api.novel')),
            ],
            options={
                'verbose_name': 'Novel alias',
                'verbose_name_plural': 'Novel aliases',
                'ordering': ['slug'],
            },
        ),
    ]
