import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


CONVERT_IMAGES_SQL = """
CREATE FUNCTION pg_temp.jsonb_to_textarr(jsonb) RETURNS varchar(500)[] LANGUAGE sql IMMUTABLE AS
$$
    SELECT CASE jsonb_typeof($1)
        WHEN 'array'  THEN ARRAY(SELECT jsonb_array_elements_text($1))
        WHEN 'object' THEN ARRAY(SELECT jsonb_object_keys($1))
        ELSE ARRAY[]::text[]
    END::varchar(500)[]
$$;
ALTER TABLE lncrawler_api_chapter
    ALTER COLUMN images TYPE varchar(500)[] USING pg_temp.jsonb_to_textarr(images);
"""

CONVERT_SOURCE_PK_SQL = """
CREATE TEMP TABLE _nfs_map AS
    SELECT id AS old_id, (row_number() OVER (ORDER BY id))::bigint AS new_id
    FROM lncrawler_api_novelfromsource;
CREATE FUNCTION pg_temp.nfs_map(uuid) RETURNS bigint LANGUAGE sql STABLE AS
$$ SELECT new_id FROM _nfs_map WHERE old_id = $1 $$;

ALTER TABLE lncrawler_api_chapter DROP CONSTRAINT lncrawler_api_chapte_novel_from_source_id_c7ee0efe_fk_lncrawler;
ALTER TABLE lncrawler_api_volume DROP CONSTRAINT lncrawler_api_volume_novel_from_source_id_16980e2b_fk_lncrawler;
ALTER TABLE lncrawler_api_sourcevote DROP CONSTRAINT lncrawler_api_source_source_id_949a8ca8_fk_lncrawler;
ALTER TABLE lncrawler_api_readinghistory DROP CONSTRAINT lncrawler_api_readin_source_id_310b0f7c_fk_lncrawler;
ALTER TABLE lncrawler_api_novelfromsource_tags DROP CONSTRAINT lncrawler_api_novelf_novelfromsource_id_51141121_fk_lncrawler;
ALTER TABLE lncrawler_api_novelfromsource_authors DROP CONSTRAINT lncrawler_api_novelf_novelfromsource_id_35d5877a_fk_lncrawler;
ALTER TABLE lncrawler_api_novelfromsource_editors DROP CONSTRAINT lncrawler_api_novelf_novelfromsource_id_6b8bc160_fk_lncrawler;
ALTER TABLE lncrawler_api_novelfromsource_translators DROP CONSTRAINT lncrawler_api_novelf_novelfromsource_id_4079a32a_fk_lncrawler;

ALTER TABLE lncrawler_api_chapter ALTER COLUMN novel_from_source_id TYPE bigint USING pg_temp.nfs_map(novel_from_source_id);
ALTER TABLE lncrawler_api_volume ALTER COLUMN novel_from_source_id TYPE bigint USING pg_temp.nfs_map(novel_from_source_id);
ALTER TABLE lncrawler_api_sourcevote ALTER COLUMN source_id TYPE bigint USING pg_temp.nfs_map(source_id);
ALTER TABLE lncrawler_api_readinghistory ALTER COLUMN source_id TYPE bigint USING pg_temp.nfs_map(source_id);
ALTER TABLE lncrawler_api_novelfromsource_tags ALTER COLUMN novelfromsource_id TYPE bigint USING pg_temp.nfs_map(novelfromsource_id);
ALTER TABLE lncrawler_api_novelfromsource_authors ALTER COLUMN novelfromsource_id TYPE bigint USING pg_temp.nfs_map(novelfromsource_id);
ALTER TABLE lncrawler_api_novelfromsource_editors ALTER COLUMN novelfromsource_id TYPE bigint USING pg_temp.nfs_map(novelfromsource_id);
ALTER TABLE lncrawler_api_novelfromsource_translators ALTER COLUMN novelfromsource_id TYPE bigint USING pg_temp.nfs_map(novelfromsource_id);

ALTER TABLE lncrawler_api_novelfromsource ALTER COLUMN id TYPE bigint USING pg_temp.nfs_map(id);
ALTER TABLE lncrawler_api_novelfromsource ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('lncrawler_api_novelfromsource', 'id'), (SELECT max(id) FROM lncrawler_api_novelfromsource));

ALTER TABLE lncrawler_api_chapter ADD CONSTRAINT lncrawler_api_chapte_novel_from_source_id_c7ee0efe_fk_lncrawler FOREIGN KEY (novel_from_source_id) REFERENCES lncrawler_api_novelfromsource(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lncrawler_api_volume ADD CONSTRAINT lncrawler_api_volume_novel_from_source_id_16980e2b_fk_lncrawler FOREIGN KEY (novel_from_source_id) REFERENCES lncrawler_api_novelfromsource(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lncrawler_api_sourcevote ADD CONSTRAINT lncrawler_api_source_source_id_949a8ca8_fk_lncrawler FOREIGN KEY (source_id) REFERENCES lncrawler_api_novelfromsource(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lncrawler_api_readinghistory ADD CONSTRAINT lncrawler_api_readin_source_id_310b0f7c_fk_lncrawler FOREIGN KEY (source_id) REFERENCES lncrawler_api_novelfromsource(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lncrawler_api_novelfromsource_tags ADD CONSTRAINT lncrawler_api_novelf_novelfromsource_id_51141121_fk_lncrawler FOREIGN KEY (novelfromsource_id) REFERENCES lncrawler_api_novelfromsource(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lncrawler_api_novelfromsource_authors ADD CONSTRAINT lncrawler_api_novelf_novelfromsource_id_35d5877a_fk_lncrawler FOREIGN KEY (novelfromsource_id) REFERENCES lncrawler_api_novelfromsource(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lncrawler_api_novelfromsource_editors ADD CONSTRAINT lncrawler_api_novelf_novelfromsource_id_6b8bc160_fk_lncrawler FOREIGN KEY (novelfromsource_id) REFERENCES lncrawler_api_novelfromsource(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE lncrawler_api_novelfromsource_translators ADD CONSTRAINT lncrawler_api_novelf_novelfromsource_id_4079a32a_fk_lncrawler FOREIGN KEY (novelfromsource_id) REFERENCES lncrawler_api_novelfromsource(id) DEFERRABLE INITIALLY DEFERRED;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('lncrawler_api', '0041_novelalias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='word_count',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='chapter',
                    name='images',
                    field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list, size=None),
                ),
            ],
            database_operations=[
                migrations.RunSQL(CONVERT_IMAGES_SQL),
            ],
        ),
        migrations.AlterField(
            model_name='chapter',
            name='novel_from_source',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='lncrawler_api.novelfromsource'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='novelfromsource',
                    name='id',
                    field=models.BigAutoField(primary_key=True, serialize=False),
                ),
            ],
            database_operations=[
                migrations.RunSQL(CONVERT_SOURCE_PK_SQL),
            ],
        ),
        migrations.AlterField(
            model_name='volume',
            name='novel_from_source',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='lncrawler_api.novelfromsource'),
        ),
    ]
