# Generated by Django 6.1.1 on 2026-10-03 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lncrawler_api', '0044_weekly_source_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='lncrawler_api.tag')),
            ],
            options={
                'verbose_name': 'tag alias',
                'verbose_name_plural': 'tag aliases',
                'ordering': ['name'],
            },
        ),
    ]
