# Generated by Django 6.1.1 on 2026-10-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lncrawler_api', '0048_friendship_profilepinnednovel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='novelfromsource',
            name='alternative_titles',
            field=models.ManyToManyField(blank=True, related_name='novels', to='lncrawler_api.alternativetitle'),
        ),
    ]
