# Generated by Django 6.1.1 on 2026-10-04 11:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lncrawler_api', '0049_alternativetitle_novelfromsource_alternative_titles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='novelbookmark',
            options={'ordering': ['position', '-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='novelrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='novelbookmark',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='novelbookmark',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='novelrating',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novel_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='novelrating',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='novelrating',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('novel', 'user'), name='unique_rating_per_user'),
        ),
        migrations.AddConstraint(
            model_name='novelrating',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('novel', 'ip_address'), name='unique_rating_per_anon_ip'),
        ),
        migrations.AddField(
            model_name='libraryfolder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='novelbookmark',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookmarks', to='lncrawler_api.libraryfolder'),
        ),
        migrations.AlterUniqueTogether(
            name='libraryfolder',
            unique_together={('user', 'name')},
        ),
    ]
