# Generated by Django 6.1.1 on 2026-10-05 15:02

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lncrawler_api', '0057_remove_board'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='alternativetitle',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='gin_trgm_ops'), name='alttitle_name_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='gin_trgm_ops'), name='author_name_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='novel',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('title'), name='gin_trgm_ops'), name='novel_title_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='novelfromsource',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('synopsis'), name='gin_trgm_ops'), name='nfs_synopsis_trgm_idx'),
        ),
    ]
