# Generated by Django 6.1.1 on 2026-10-05 19:23

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lncrawler_api', '0058_trgm_search_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tag',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='gin_trgm_ops'), name='tag_name_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='tagalias',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='gin_trgm_ops'), name='tagalias_name_trgm_idx'),
        ),
    ]
