# Generated by Django 6.1.1 on 2026-10-07 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lncrawler_api', '0059_tag_trgm_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('muted_sources', models.JSONField(blank=True, default=list)),
                ('max_concurrent', models.PositiveIntegerField(default=3)),
                ('last_harvest_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lncrawler_api_harvestconfig',
            },
        ),
        migrations.CreateModel(
            name='HarvestCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(db_index=True, max_length=255)),
                ('novel_url', models.CharField(max_length=512, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('job_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lncrawler_api_harvestcandidate',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'source_name'], name='lncrawler_a_status_ad1691_idx')],
            },
        ),
    ]
