# Generated by Django 6.1.1 on 2026-10-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lncrawler_api', '0060_harvestconfig_harvestcandidate'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(condition=models.Q(('status', 'created')), fields=['status', 'created_at'], name='job_claim_idx'),
        ),
    ]
