# Generated by Django 6.1.1 on 2026-10-09 09:59

import django.db.models.deletion
import django.db.models.functions.comparison
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lncrawler_api', '0063_remove_novelfromsource_unused_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelfromsource',
            name='cover_phash',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='MergeCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('novel_a_id_snapshot', models.UUIDField(blank=True, null=True)),
                ('novel_b_id_snapshot', models.UUIDField(blank=True, null=True)),
                ('title_a', models.CharField(blank=True, default='', max_length=255)),
                ('title_b', models.CharField(blank=True, default='', max_length=255)),
                ('certainty', models.FloatField(db_index=True, default=0.0)),
                ('signals', models.JSONField(blank=True, default=dict)),
                ('decision', models.CharField(choices=[('auto', 'Auto'), ('review', 'Review')], db_index=True, default='review', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('merged', 'Merged'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=10)),
                ('llm_verdict', models.JSONField(blank=True, null=True)),
                ('llm_reason', models.TextField(blank=True, default='')),
                ('llm_model', models.CharField(blank=True, default='', max_length=100)),
                ('llm_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('novel_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_candidates_as_a', to='lncrawler_api.novel')),
                ('novel_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_candidates_as_b', to='lncrawler_api.novel')),
            ],
            options={
                'db_table': 'lncrawler_api_mergecandidate',
                'ordering': ['-certainty'],
                'indexes': [models.Index(fields=['status', '-certainty'], name='mergecand_status_cert_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('novel_a', models.F('novel_b')), _negated=True), name='mergecandidate_no_self'), models.UniqueConstraint(django.db.models.functions.comparison.Least('novel_a', 'novel_b'), django.db.models.functions.comparison.Greatest('novel_a', 'novel_b'), name='mergecandidate_unique_pair')],
            },
        ),
    ]
