# Generated by Django 6.1.1 on 2026-10-09 17:52

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lncrawler_api', '0064_novelfromsource_cover_phash_mergecandidate'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mergecandidate',
            name='mergecandidate_unique_pair',
        ),
        migrations.AddConstraint(
            model_name='mergecandidate',
            constraint=models.UniqueConstraint(django.db.models.functions.comparison.Least('novel_a', 'novel_b'), django.db.models.functions.comparison.Greatest('novel_a', 'novel_b'), condition=models.Q(('novel_a__isnull', False), ('novel_b__isnull', False)), name='mergecandidate_unique_pair'),
        ),
    ]
