# Generated by Django 6.1.1 on 2026-10-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lncrawler_api', '0065_remove_mergecandidate_mergecandidate_unique_pair_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='novel',
            index=models.Index(fields=['title'], name='novel_title_idx'),
        ),
    ]
