"""
Django settings for api_project project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import urlparse
from pathlib import Path
from dotenv import load_dotenv
load_dotenv(encoding='utf-8')

SITE_URL = os.environ.get("SITE_URL", "http://localhost:8185").rstrip("/")
SITE_API_URL = os.environ.get("SITE_API_URL", "http://localhost:8000").rstrip("/")
# Origins keep the port (browser Origin includes it for non-default ports), but
# ALLOWED_HOSTS and the cookie domain must be the bare hostname: nginx forwards
# `Host` without the port.
SITE_DOMAIN = urlparse(SITE_URL).hostname or ""
API_DOMAIN = urlparse(SITE_API_URL).hostname or ""


SECRET_KEY = os.environ.get("SECRET_KEY")

DEBUG = os.environ.get("DEBUG", "False") == "True"

CORS_ALLOWED_ORIGINS = [
    SITE_URL,
    SITE_API_URL,
]
ALLOWED_HOSTS = [
    SITE_DOMAIN,
    API_DOMAIN,
    'localhost',
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_ALL_ORIGINS = os.environ.get("CORS_ALLOW_ALL_ORIGINS", "False") == "True"
# Credentialed CORS with a wildcard origin is unsafe (and browsers reject it).
# Force credentials off whenever every origin is allowed.
if CORS_ALLOW_ALL_ORIGINS:
    CORS_ALLOW_CREDENTIALS = False

CSRF_TRUSTED_ORIGINS = [
    SITE_URL,
    SITE_API_URL,
]
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_COOKIE_HTTPONLY = False 
CSRF_USE_SESSIONS = False
CSRF_COOKIE_SAMESITE = 'Lax' 

# Security settings for HTTPS
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_DOMAIN = SITE_DOMAIN
else:
    SECURE_PROXY_SSL_HEADER = None
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    CSRF_COOKIE_DOMAIN = None


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'lncrawler_api',
    'auth_app',
    'django.contrib.sitemaps',
    'rest_framework.authtoken',
    'django.contrib.postgres',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware must be at the top
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "api_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "api_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'lncrawler'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'postgres'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        # Read-heavy public API: most requests are pure reads, so we avoid
        # wrapping every request in a transaction. Write views rely on
        # ATOMIC_REQUESTS-off semantics; keep transactions explicit where needed.
        'ATOMIC_REQUESTS': False,
        # Reuse the connection between requests instead of reconnecting each time.
        'CONN_MAX_AGE': 60,
        'CONN_HEALTH_CHECKS': True,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [
]

MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_FULL_URL = SITE_URL.rstrip("/") + "/" + MEDIA_URL.rstrip("/") + "/"

LNCRAWL_OUTPUT_PATH = os.path.join(BASE_DIR.parent, 'Lightnovels')
LNCRAWL_URL = "lightnovels/"
LNCRAWL_FULL_URL = SITE_URL.rstrip("/") + "/" + LNCRAWL_URL.rstrip("/") + "/"

# Hours a generated EPUB is reused before being rebuilt even if the source
# hasn't changed. Also invalidated immediately when the source is updated.
EPUB_CACHE_HOURS = int(os.environ.get("EPUB_CACHE_HOURS", 24))

IMPORT_FOLDER_PATH = os.path.join(BASE_DIR.parent, 'imports')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'COERCE_DECIMAL_TO_STRING': False,
    # Scoped rates consumed by the throttle classes in auth_app.views.
    'DEFAULT_THROTTLE_RATES': {
        'login': os.environ.get('THROTTLE_LOGIN', '10/min'),
        'register': os.environ.get('THROTTLE_REGISTER', '10/hour'),
        'password_reset': os.environ.get('THROTTLE_PASSWORD_RESET', '5/hour'),
        'user_exists': os.environ.get('THROTTLE_USER_EXISTS', '30/min'),
    },
}

CORS_URLS_REGEX = r"^/.*$"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = 'auth_app.CustomUser'

# Short-lived in-process cache for the anonymous home page (the heavy
# ranking aggregations). Per-worker LocMemCache; a few seconds of staleness
# for rankings is invisible to users. Not a substitute for Redis: each
# worker keeps its own copy, so it only helps repeated hits on one worker.
HOME_PAGE_CACHE_SECONDS = int(os.environ.get("HOME_PAGE_CACHE_SECONDS", "30"))

import logging

# DEBUG logging in production is expensive (record creation, formatting, I/O)
# and the crawler libraries are noisy. Default to INFO unless overridden.
LOG_LEVEL = os.environ.get("LOG_LEVEL", "DEBUG" if DEBUG else "INFO")

# --- GitHub issue reporting for unexpected errors ---
# When enabled, every ERROR+ log record (web, crawler, scheduler) opens a
# GitHub issue, deduplicated by fingerprint. Leave GITHUB_ISSUES_ENABLED=False
# in development so local errors do not spam the tracker.
GITHUB_REPO = os.environ.get("GITHUB_REPO", "")
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
GITHUB_ISSUES_ENABLED = os.environ.get("GITHUB_ISSUES_ENABLED", "False") == "True"
# Development alternative to the GitHub tracker: when set, each unexpected error
# writes one Markdown file per fingerprint under ISSUE_REPORTS_DIR instead of
# opening an issue. Dedup is the file already existing.
ISSUE_REPORTS_TO_DISK = os.environ.get("ISSUE_REPORTS_TO_DISK", "False") == "True"
ISSUE_REPORTS_DIR = os.environ.get(
    "ISSUE_REPORTS_DIR", os.path.join(BASE_DIR, "issue-reports")
)
# Identifies which container produced an issue: api / crawler / scheduler.
SERVICE_NAME = os.environ.get("SERVICE_NAME", "api")

# Define a custom UTF-8 stream handler
class UTF8StreamHandler(logging.StreamHandler):
    def __init__(self):
        super().__init__()
        
    def emit(self, record):
        try:
            msg = self.format(record)
            stream = self.stream
            # Ensure the message is encoded as UTF-8
            stream.write(msg + self.terminator)
            self.flush()
        except Exception:
            self.handleError(record)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'django_formatter': {
            'format': '[DJANGO] {levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'lncrawler_api_formatter': {
            'format': '[LNCrawlerAPI] {levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'django_console': {
            'class': 'api_project.settings.UTF8StreamHandler',
            'formatter': 'django_formatter',
            'level': LOG_LEVEL,
        },
        'lncrawler_api_console': {
            'class': 'api_project.settings.UTF8StreamHandler',
            'formatter': 'lncrawler_api_formatter',
            'level': LOG_LEVEL,
        },
        'django_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'django_formatter',
            'encoding': 'utf-8',
            'level': LOG_LEVEL,
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
        },
        'lncrawler_api_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'lncrawler_api.log'),
            'formatter': 'lncrawler_api_formatter',
            'encoding': 'utf-8',
            'level': LOG_LEVEL,
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
        },
        'github_issues': {
            # Non-blocking: enqueues to a background thread and opens a GitHub
            # issue for ERROR+ records. No-op unless GITHUB_* settings are set.
            'class': 'api_project.logging_handlers.GitHubIssueHandler',
            'level': 'ERROR',
        },
    },
    'loggers': {
        'django': {  # Django's built-in logger
            'handlers': ['django_console', 'django_file', 'github_issues'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'lncrawler_api': { 
            'handlers': ['lncrawler_api_console', 'lncrawler_api_file', 'github_issues'],

            'level': LOG_LEVEL,
            'propagate': False,
        },
        'lncrawl': {  # The lncrawler-crawler library
            'handlers': ['lncrawler_api_console', 'lncrawler_api_file', 'github_issues'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'frontend': {  # Errors reported by the browser via /report-error/
            'handlers': ['lncrawler_api_console', 'lncrawler_api_file', 'github_issues'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'auth_app': {  # Otherwise propagates to a handler-less root logger
            'handlers': ['lncrawler_api_console', 'lncrawler_api_file', 'github_issues'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)


# Email settings — standard SMTP, provider-agnostic. Swapping providers is a
# config change only. MailPace: host smtp.mailpace.com, port 587 (STARTTLS),
# and the domain's API token as both EMAIL_HOST_USER and EMAIL_HOST_PASSWORD.
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.mailpace.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
# Local dev without credentials: print reset emails to the console instead of
# failing. Never silently enabled in production.
if DEBUG and not EMAIL_HOST_USER:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "no-reply@lncrawler.monster")
EMAIL_SENDER_NAME = os.environ.get("EMAIL_SENDER_NAME", "LNCrawler")