"""
Django settings for api_project project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()

SITE_URL = os.environ.get("SITE_URL", "http://localhost:5173")
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

DEBUG = os.environ.get("DEBUG", "False") == "True"

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
CORS_ORIGIN_WHITELIST = tuple(os.environ.get("CORS_ORIGIN_WHITELIST", "http://localhost:5173,http://127.0.0.1:5173").split(","))
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Security settings for HTTPS
if not DEBUG:
    SECURE_SSL_REDIRECT = True  # Redirect HTTP to HTTPS
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'lncrawler_api',
    'auth_app',
    'django.contrib.sitemaps',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware must be at the top
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "api_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "api_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_FILE_NAME = os.environ.get('DB_FILE_NAME', 'db.sqlite3')
DB_FILE_DIR = os.environ.get('DB_FILE_DIR', '')

# Construct the database path
if DB_FILE_DIR:
    DB_FILE_PATH = Path(DB_FILE_DIR) / DB_FILE_NAME
else:
    DB_FILE_PATH = BASE_DIR / DB_FILE_NAME

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DB_FILE_PATH,
        "ATOMIC_REQUESTS": True,
    }
}

import stat
DB_DIR = DB_FILE_PATH.parent
os.makedirs(DB_DIR, exist_ok=True)
if os.path.exists(DB_FILE_PATH):
    os.chmod(DB_FILE_PATH, stat.S_IRUSR | stat.S_IWUSR)  # 600 - Owner read/write only for DB file

# Backup directory - full path configuration
SQLITE_BACKUP_DIR = os.path.join(BASE_DIR, os.environ.get('SQLITE_BACKUP_DIR', 'backups'))
os.makedirs(SQLITE_BACKUP_DIR, exist_ok=True)
os.chmod(SQLITE_BACKUP_DIR, stat.S_IRWXU)  # 700 permissions for backup dir
BACKUP_RETENTION_DAYS = int(os.environ.get('BACKUP_RETENTION_DAYS', 30))



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [
]

MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_FULL_URL = SITE_URL.rstrip("/") + "/" + MEDIA_URL.rstrip("/") + "/"

LNCRAWL_OUTPUT_PATH = os.path.join(BASE_DIR, 'Lightnovels')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'COERCE_DECIMAL_TO_STRING': False,
}

CORS_URLS_REGEX = r"^/.*$"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = 'auth_app.CustomUser'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'django_formatter': {
            'format': '[DJANGO] {levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'apibot_formatter': {
            'format': '[APIBOT] {levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'lncrawler_api_formatter': {
            'format': '[LNCrawlerAPI] {levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'django_console': {
            'class': 'logging.StreamHandler',
            'formatter': 'django_formatter',
            'level': 'DEBUG',
        },
        'lncrawler_api_console': {
            'class': 'logging.StreamHandler',
            'formatter': 'lncrawler_api_formatter',
            'level': 'DEBUG',
        },
        'django_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'django_formatter',
        },
        'apibot_file': { 
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'apibot.log'),
            'formatter': 'apibot_formatter',
        },
        'lncrawler_api_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'lncrawler_api.log'),
            'formatter': 'lncrawler_api_formatter',
        },
    },
    'loggers': {
        'django': {  # Django's built-in logger
            'handlers': ['django_console', 'django_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'lncrawler_api': { 
            'handlers': ['lncrawler_api_console', 'lncrawler_api_file'],

            'level': 'DEBUG',
            'propagate': False,
        },
        'apibot': {  # Separate logger for PythonApiBot - file only, no console
            'handlers': ['apibot_file'], 
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)