# Generated by Django 5.2.1 on 2025-05-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0002_customuser_bio_customuser_profile_pic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="bio",
        ),
    ]
