# Generated by Django 5.2.1 on 2025-06-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='word_read',
            field=models.IntegerField(default=0),
        ),
    ]
