# Generated by Django 6.1.1 on 2026-10-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_alter_passwordresettoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='discoverable',
            field=models.BooleanField(default=True),
        ),
    ]
