# Generated by Django 6.1.1 on 2026-10-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_customuser_discoverable'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='show_r18',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('blur', 'Blur')], default='no', max_length=4),
        ),
    ]
