# =========================================================================
#  ONE-TIME SCRIPT -- DELETE THIS FILE AFTER RUNNING IT ON PRODUCTION.
# =========================================================================
#  The crawler used to fabricate a solid-colour + title "cover" whenever a
#  novel had no downloadable cover. That feature is gone, but the old
#  placeholder cover.jpg / cover.min.webp / overview.jpg files and their DB
#  paths are still around and pollute cover hashing / similarity. This
#  command finds and removes them once.
#
#  Run it once on prod (dry run by default, then --apply), then a maintainer
#  should delete this whole file together with <output>/.cover_cleanup_trash.
# =========================================================================
"""Remove placeholder covers generated by the retired crawler fallback.

Detection: a generated cover is a roughly solid fill of one of the 7 palette
colours (imgen.py PALETTE, hardcoded here because that module is deleted) with
a bit of centred text on top. So we flag an image whose dominant colour is
within ``--palette-tolerance`` of a palette entry, occupies at least
``--min-dominant`` of the pixels, and whose overall stddev is below
``--max-std`` (real covers are far busier).

``--apply`` is required to change anything; the default is a dry run. Matched
files are moved to ``<LNCRAWL_OUTPUT_PATH>/.cover_cleanup_trash`` (preserving
their relative path) and every change is appended to ``audit.jsonl`` there.
The source row's cover_path / cover_min_path / overview_picture_path are
nulled. ``cover_url`` is kept untouched.

This file is disposable: delete it once the production run is done.
"""

import json
import logging
import os
import shutil
import statistics
from collections import Counter
from datetime import datetime

from django.conf import settings
from django.core.management.base import BaseCommand
from PIL import Image

from lncrawler_api.models import NovelFromSource

logger = logging.getLogger("lncrawler_api")

# Copied verbatim from the deleted lncrawl/utils/imgen.py PALETTE.
PALETTE = [
    (33, 150, 243),
    (156, 39, 176),
    (233, 30, 99),
    (255, 152, 0),
    (63, 81, 181),
    (0, 150, 136),
    (121, 85, 72),
]

THUMB = (64, 64)


def _closest_palette_distance(color):
    r, g, b = color
    return min(
        max(abs(r - pr), abs(g - pg), abs(b - pb)) for pr, pg, pb in PALETTE
    )


def is_generated_cover(path, min_dominant, max_std, palette_tolerance):
    """Return (True, dominant_color) when the image looks like a placeholder."""
    try:
        with Image.open(path) as img:
            img = img.convert("RGB").resize(THUMB, Image.Resampling.LANCZOS)
            pixels = list(img.getdata())
    except Exception as e:
        logger.warning("Could not read cover %s: %s", path, e)
        return False, None

    if not pixels:
        return False, None

    dominant, count = Counter(pixels).most_common(1)[0]
    dominant_ratio = count / len(pixels)

    channels = list(zip(*pixels))
    std = statistics.fmean(statistics.pstdev(ch) for ch in channels)

    matches_palette = _closest_palette_distance(dominant) <= palette_tolerance
    return (matches_palette and dominant_ratio >= min_dominant and std <= max_std), dominant


class Command(BaseCommand):
    help = (
        "ONE-TIME: remove crawler-generated placeholder covers. "
        "Delete this command after running it on production."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--apply",
            action="store_true",
            help="Actually move files and null paths. Without it: dry run.",
        )
        parser.add_argument(
            "--min-dominant", type=float, default=0.6,
            help="Min share of pixels matching the dominant palette colour (default 0.6).",
        )
        parser.add_argument(
            "--max-std", type=float, default=20.0,
            help="Max overall pixel stddev for a flat placeholder (default 20).",
        )
        parser.add_argument(
            "--palette-tolerance", type=int, default=30,
            help="Per-channel tolerance to the palette colour (default 30).",
        )
        parser.add_argument(
            "--source", type=str, default=None,
            help="Only scan this ExternalSource name.",
        )
        parser.add_argument(
            "--limit", type=int, default=0,
            help="Max sources to examine (0 = all).",
        )
        parser.add_argument(
            "--sleep", type=float, default=0.0,
            help="Seconds to sleep between processed sources.",
        )

    def handle(self, *args, **options):
        import time

        self.apply = options["apply"]
        self.min_dominant = options["min_dominant"]
        self.max_std = options["max_std"]
        self.palette_tolerance = options["palette_tolerance"]
        self.sleep = options["sleep"]
        self.limit = options["limit"]

        self.root = settings.LNCRAWL_OUTPUT_PATH
        self.trash_root = os.path.join(self.root, ".cover_cleanup_trash")

        qs = NovelFromSource.objects.select_related("external_source").order_by("pk")
        if options["source"]:
            qs = qs.filter(external_source__source_name=options["source"])
        if self.limit:
            qs = qs[: self.limit]

        mode = "APPLY" if self.apply else "DRY-RUN"
        self.stdout.write(self.style.WARNING(f"=== {mode} ==="))

        examined = 0
        matched = 0
        per_source = Counter()
        for source in qs.iterator():
            examined += 1
            cover_abs = self._abs(source.cover_path) if source.cover_path else None
            if not cover_abs or not os.path.isfile(cover_abs):
                continue

            generated, dominant = is_generated_cover(
                cover_abs, self.min_dominant, self.max_std, self.palette_tolerance
            )
            if not generated:
                continue

            matched += 1
            name = source.external_source.source_name if source.external_source else "?"
            per_source[name] += 1
            self.stdout.write(
                f"[{name}] {source.title!r} dominant={dominant} cover_url={source.cover_url!r}"
            )

            if self.apply:
                self._purge(source, dominant)
            if self.sleep:
                time.sleep(self.sleep)

        self.stdout.write("")
        self.stdout.write(f"Examined {examined} sources, matched {matched} placeholders.")
        for name, count in per_source.most_common():
            self.stdout.write(f"  {count:5d}  {name}")
        if not self.apply and matched:
            self.stdout.write(self.style.WARNING("Dry run: nothing changed. Re-run with --apply."))
        if self.apply and matched:
            self.stdout.write(f"Moved files to {self.trash_root} (delete when done).")
        self.stdout.write(self.style.ERROR("Remember: delete this command file after use."))

    def _abs(self, rel_path):
        base = os.path.realpath(self.root)
        abs_path = os.path.realpath(os.path.join(base, rel_path))
        if abs_path != base and not abs_path.startswith(base + os.sep):
            raise ValueError(f"refusing path outside output root: {rel_path!r}")
        return abs_path

    def _move_to_trash(self, rel_path):
        abs_src = self._abs(rel_path)
        if not os.path.isfile(abs_src):
            return None
        dest = os.path.join(self.trash_root, rel_path)
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        if os.path.exists(dest):
            stamp = datetime.now().strftime("%Y%m%d%H%M%S")
            dest = f"{dest}.{stamp}"
        shutil.move(abs_src, dest)
        return dest

    def _purge(self, source, dominant):
        removed = []
        for field in ("cover_path", "cover_min_path", "overview_picture_path"):
            rel = getattr(source, field)
            if rel:
                moved = self._move_to_trash(rel)
                if moved:
                    removed.append(rel)
                setattr(source, field, None)
        source.cover_phash = None
        source.save(update_fields=[
            "cover_path", "cover_min_path", "overview_picture_path", "cover_phash"
        ])

        os.makedirs(self.trash_root, exist_ok=True)
        entry = {
            "ts": datetime.now().isoformat(),
            "source_id": str(source.pk),
            "external_source": (
                source.external_source.source_name if source.external_source else None
            ),
            "cover_url": source.cover_url,
            "dominant": dominant,
            "removed": removed,
        }
        with open(os.path.join(self.trash_root, "audit.jsonl"), "a", encoding="utf-8") as fh:
            fh.write(json.dumps(entry, default=str) + "\n")
